### ISSUE TITLE
Installation Problems - commandServer.py

### ISSUE THREAD

**Issue by pengzhenjia** [jhmlam/NucleicNet#3]
Dear professor, I am a graduate student at Central South University in China. I am recently trying to install your NucleicNet package locally. But I encounter a problem when I run it following the /NucleicNet/Notebooks07_DownstreamApplication.ipynb. The following is the python error that I got.

**Traceback (most recent call last):
  File "run.py", line 112, in <module>
    ServerC.MakeSXPR(aux_id=0, Checkpointlist = [   # NOTE These three models (with gelu) 
  File "/home/li_server3/jiapengzhen/NucleicNet/NucleicNet/Notebooks/../NucleicNet/DatasetBuilding/commandServer.py", line 735, in MakeSXPR
    result_df, result_df_modelaveraged, ClassName_ClassIndex_Dict = PredictionWrapperC.Run(aux_id = aux_id)
  File "/home/li_server3/jiapengzhen/NucleicNet/NucleicNet/Notebooks/../NucleicNet/DatasetBuilding/commandServer.py", line 511, in Run
    benchmark_df = PredictionHelperC.Testing(ckp_hyperparam)
  File "/home/li_server3/jiapengzhen/NucleicNet/NucleicNet/Notebooks/../NucleicNet/DatasetBuilding/commandServer.py", line 329, in Testing
    test_benchmark = self.Diagnose(Testing_PdbidBatches, ckp_hyperparam)
  File "/home/li_server3/jiapengzhen/NucleicNet/NucleicNet/Notebooks/../NucleicNet/DatasetBuilding/commandServer.py", line 169, in Diagnose
    ds_ = self.FetchDatasetC.GetNoOpSingleDataset(
AttributeError: 'FetchDataset' object has no attribute 'GetNoOpSingleDataset'**

I find that the class FetchDataset at /NucleicNet/DatasetBuilding/commandDataFetcher.py has no attribute 'GetNoOpSingleDataset'.
Could you help me to solve it?
Thanks very much.

**Comment by jhmlam** [comment]
Dear @MNXIAOJIA123 , 

Thanks for the test run and sorry for the confusion! 
I have now uploaded the commandDataFetcher.py with the attribute. Please replace it with the original commandDataFetcher.py downloaded before. Surely let me know there are other problems.

Just a check in have you run through Notebook00 as well? I see that we actually need `chmod -R 777 NucleicNet/NucleicNet/util/` so that the executables (dssp and Feature) runs properly.

Let me know if there are other errors.

Best,
Jordy
